sudo: required
language: cpp
osx_image: xcode11.3
os:
  - osx

env:
#  - LLVM_VERSION=3.9
#  - LLVM_VERSION=4.0
#  - LLVM_VERSION=5.0
#  - LLVM_VERSION=6.0
#  - LLVM_VERSION=7.0
#  - LLVM_VERSION=8.0
  - LLVM_VERSION=9.0

before_script:
  - |
    export version=`grep -Eo "MULL_VERSION [0-9.]+" CMakeLists.txt | awk ' { print $2 } '`

    case $TRAVIS_EVENT_TYPE in
      "pull_request")
        export suffix=-pr$TRAVIS_PULL_REQUEST
        export package=mull-nightly
        export channel=nightly
      ;;
      "push")
        if [ "$TRAVIS_TAG-" != "-" ];
        then
          export suffix=""
          export package=mull
          export channel=stable
          if [ $TRAVIS_TAG != $version ];
          then
            echo $version
            echo $suffix
            echo $package
            echo $channel
            false
          fi
        else
          export suffix=-trunk`git rev-list HEAD --count`
          export package=mull-nightly
          export channel=nightly
        fi
      ;;
      *)
        false
      ;;
    esac

script:
  - |
    echo $version
    echo $suffix
    echo $package
    echo $channel

# - script: sudo easy_install pip && sudo pip install ansible
