name: Example workflow yml

on: [push]

# https://github.com/mull-project/mull/releases/download/0.6.1/Mull-0.6.1-LLVM-8.0-ubuntu-18.04.deb

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download package
        run: |
          wget https://github.com/mull-project/mull/releases/download/0.6.1/Mull-0.6.1-LLVM-8.0-ubuntu-18.04.deb -O /tmp/Mull-0.6.1-LLVM-8.0-ubuntu-18.04.deb
      - name: Upload deb package to Bintray
        uses: bpicode/github-action-upload-bintray@master
        with:
          file: /tmp/Mull-0.6.1-LLVM-8.0-ubuntu-18.04.deb
          api_user:
          api_key: ${{ secrets.BINTRAY_API_KEY }} # An API key can be obtained from the user profile page.
          repository_user: mull-project
          repository: ubuntu
          package: mull
          version: '0.6.1'
          publish: 1
          calculate_metadata: true
          deb_distribution: latest
          deb_component: main
          deb_architecture: amd64